
-- Создание таблицы чат-комнат
CREATE TABLE chat_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи для пользователей
    CONSTRAINT fk_chat_room_user1
        FOREIGN KEY (user1_id) REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_room_user2
        FOREIGN KEY (user2_id) REFERENCES users(id)
        ON DELETE CASCADE,

    -- Уникальная комбинация пользователей (в любом порядке)
    CONSTRAINT uq_user_pair
        CHECK (user1_id < user2_id),

    CONSTRAINT unique_user_pair
        UNIQUE (user1_id, user2_id)
);

-- Создание таблицы сообщений
CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatroom_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи
    CONSTRAINT fk_chat_message_room
        FOREIGN KEY (chatroom_id) REFERENCES chat_room(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_message_sender
        FOREIGN KEY (sender_id) REFERENCES users(id)
        ON DELETE CASCADE
);

-- Оптимизация для частых запросов
CREATE INDEX idx_chat_message_room ON chat_message(chatroom_id);
CREATE INDEX idx_chat_message_sender ON chat_message(sender_id);
CREATE INDEX idx_chat_message_time ON chat_message(date_time);